version: '2'
services:
  web:
    build: .
    ports:
    - "8002:8000"
    depends_on:
    - db
    restart: always
  db:
   image: vulhub/oracle:12c-ee
   restart: on-failure
networks:
  default:
    name: lab-net
    external: true