services:
 samba:
   image: vulhub/samba:4.6.3
   tty: true
   volumes:
    - ./smb.conf:/usr/local/samba/etc/smb.conf
   ports:
    - "445:445"
    - "6699:6699"
networks:
  default:
    name: lab-net
    external: true