version: '2'
services:
 dns:
   image: vulhub/bind:latest
   expose:
    - "53/tcp"
    - "53/udp"
   volumes:
    - ./named.conf.local:/etc/bind/named.conf.local
    - ./vulhub.db:/etc/bind/vulhub.db
networks:
  default:
    name: lab-net
    external: true